### ISSUE TITLE
Set up more examples

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/pymc3#11]
Examples using pymc3 with MLDA:
- [x] Gravity
- [x] Predator Prey
- [x] Other examples for paper
- [x] Comparison with more MCMC samplers - benchmarks
- [x] Different parameters/settings exploration

**Comment by gmingas** [comment]
@mikkelbue Regarding the Gravity example, I noticed you have set the tuning interval to a high value so that no tuning happens, what is the reason behind that?

Also, do the pictures at the end show a big difference between the true model and the inferred ones? Is this expected?

**Comment by mikkelbue** [comment]
@gmingas I just wanted a comparison between "pure" Metropolis and MLDA, with no fancy tuning. You are welcome to change that.

The difference between the true model and the inferred one is largely down to the low confidence in the data, I think the variance of the data was set to 10.0, right? So that means that the (zero-mean) prior becomes dominant in the unormalised posterior, resulting in a smoother solution. If you reduce the variance, you will get a much more close-fitting solution.

**Comment by mikkelbue** [comment]
@gmingas I just saw you mail about the gravity example. If there is a big misfit between the true solution and the recovered one, it may also be because the random process KL decomposition is truncated too aggressively. You can't recover a function of that complexity with only 4 KL modes.
