### ISSUE TITLE
Random subsampling rate in each iteration

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/pymc3#74]

**Comment by tjdodwell** [comment]
@gmingas, I had another discussion with Colin this evening. For the theory to work out you can't truncate the coarse chain, otherwise you get a bias on the length of the coarse chain.

So you have to run the subchain for a fixed length. You then simple have to pass a random sample from the subchain as the proposal.

This should be easier for you to implement. It also doesn't affect size container like the other option we discussed.

**Comment by tjdodwell** [comment]
@gmingas, I had another discussion with Colin this evening. For the theory to work out you can't truncate the coarse chain, otherwise you get a bias.

So you have to run the subchain for a fixed length. You then simply have to pass a random sample from the subchain as the proposal.

This should be easier for you to implement. It also doesn't affect size container like the other option we discussed.

Getting there :)

**Comment by gmingas** [comment]
OK, makes sense. This is a bit more difficult to implement due to AEM assuming that the last sample of the coarse chain is the proposal but I am working on it, I will let you know soon.

**Comment by gmingas** [comment]
@tjdodwell Do you want the random subsampling to happen always or would you like to be able to deactivate it with a boolean argument on MLDA? Phrased differently, is the existing non-random subsampling theoretically correct and/or something we want to keep as an option?

**Comment by tjdodwell** [comment]
@gmingas theoretical for the sampler and variance reduction to work you need to do the random subsampling.

For the sampler to work, you don't need to always compute all subchains to a full fixed length. For variance reduction you do, since otherwise you have to do some re-weighting in the estimators, which would be nasty.

I think it is cleaner to have a single sampling approach. I.e. run a fixed length subchain, from that subchain sample at random one of the those samples to be taken up as a proposal.

**Comment by gmingas** [comment]
[This](https://github.com/alan-turing-institute/pymc3/tree/feature/random-subsample-length) branch now contains the randomised selection version for the subchain, along with rerun notebooks.

It looks like it is functionally correct but the ESS is reduced somewhat compared to the previous non-randomised version. You can see this in all the notebooks. This is I think expected given that you tend to propose samples that are more correlated with the starting sample from the fine chain.

@tjdodwell @mikkelbue please test on your other examples to see if it breaks.

**Comment by gmingas** [comment]
@tjdodwell 

I made the switch as discussed. Now subchains have a random length (with max equal to the subsampling rate) when variance reduction is not used and the last sample is selected as a proposal. When variance reduction is used subchains have constant length equal to the subsampling rate and a randomly selected sample from the sequence is used as a proposal.

With this new setting I still get a reduction in ESS (expected) but no corresponding reduction in runtime as expected due to the shorter chains (in the non-VR setting). At least this is what is happening in the gravity example notebook. One explanation could be that the cost of setting up a subchain and doing all the overhead is much bigger that the difference in cost between generating 3 and 5 samples (subsampling rate is 5 in this example). Maybe any gains could become apparent with larger subsampling rates.

**Comment by mikkelbue** [comment]
Hi both

Sorry maybe I am a bit slow, and I am not sure I completely understand the VR theory. But why would we not run subchains to their full length, when VR is _not_ active? Seems like a waste of calls to subsample. If there is no problem in the theory to run fixed length subschains, I think it's better to max out their length for the gain in ESS.

That would also make the implementation a lot cleaner, since the only difference in VR would be to return a random element of the fixed length trace.

Mikkel

**Comment by gmingas** [comment]
I think the idea was that there is some theoretical reason to run subchains of random length (even without VR). But if this is not the case I agree with Mikkel, given the results I have been seeing.

**Comment by tjdodwell** [comment]
For sampling you can run the fixed length chain. I was keen to see the difference between them, as if there wasn't you want to use the same implementation

**Comment by gmingas** [comment]
OK, just to be clear, is this what we want now?
- When VR is not used: Fixed subchain length and select the last sample of the subchain (i.e. no randomisation)
- When VR is used: Fixed subchain length and select a random sample from the subchain.

**Comment by tjdodwell** [comment]
Yes

Prof. Tim Dodwell
Chair in Computational Mechanics,
Turing AI Fellow,

Rm 111 - Harrison Building
College of Engineering, Mathematics & Physical Sciences
University of Exeter
Exeter
Devon
EX4 4PY

mail: t.dodwell@exeter.ac.uk<mailto:t.dodwell@exeter.ac.uk>
tel: +44 (0)1392 725899
mob: +44 (0)7745 622870
web: http://emps.exeter.ac.uk/engineering/staff/td336

Research Manager Data Centric Engineering Group – Ms Yujin Du (Y.Du@exeter.ac.uk<mailto:Y.Du@exeter.ac.uk>)
