### ISSUE TITLE
Format the code for second PR

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/pymc3#84]
As the PR review has now been assigned to our team, the following things need to be done:
- Run [black](https://github.com/psf/black) on mlda.py and the sections of test_step.py that relate to MLDA (this can be done by copy pasting the TestMLDA class to another file, blackening the file and copy pasting the result back to test_step.py)
- Apply [typing](https://docs.python.org/3/library/typing.html) to any new method arguments since the previous PR. These are keywords added next to the method arguments when defining the method. You will see many of them already there in MLDA class' __init__. It is not necessary to do it for everything, only if you think some of the new functions would benefit from this extra clarity.
- Decide if the benchmark and groundwater notebooks should be included in the external links (they are a bit outdated so if we keep them they should be rerun and it will take some time for the former).

**Comment by mikkelbue** [comment]
@gmingas Okay, that sounds good. I don't think there is any point of including the groundwater flow notebook, since that is also covered in the AEM notebook. But I will have a look at the benchmarks/tuning one, and rerun it over the weekend.

I'll look at the other changes during the weekend too, or possibly early next week.

**Comment by mikkelbue** [comment]
Okay, this is fixed with https://github.com/alan-turing-institute/pymc3/commit/06b66973b53d87344de381dcf8089ab80150f9b8, https://github.com/alan-turing-institute/pymc3/commit/50436ec6aa06e481951ebb309510e5db4d738f1a and https://github.com/alan-turing-institute/pymc3/commit/14d15bfedf8380dcd0924b7e759ab401f175ba94.

I removed the link to he groundwater notebook, since that is covered by the AEM notebook, and reorganised the introduction notebook slightly.

I will rerun the benchmarks and tuning notebook and push to the mlda_all_notebooks branch.
